fix: AroundPrecision serialization in multipleQueries
[changelog]
using aroundPrecision in multipleQueries would cause
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.CharSequence